### ISSUE TITLE
A problem while training the model

### ISSUE THREAD

**Issue by HananAbdulla** [Nikolai10/scrabble-gan#14]
Thanks for your great work

I got a problem while training the model 
![error](https://user-images.githubusercontent.com/16627947/164991256-af191905-2625-4df8-bdbb-d5798edf0320.png)
please help be in solving the problem?

Thanks;

**Comment by Nikolai10** [comment]
Hello @HananAbdulla, 

OOM = out-of-memory. To overcome this issue, e.g. try to reduce the batch size:

`shared_specs.batch_size = 64` -> 32 (16, 8, 4, ...)
(in [scrabble_gan.gin](https://github.com/Nikolai10/scrabble-gan/blob/master/src/scrabble_gan.gin)).

Hope that helps!

**Comment by HananAbdulla** [comment]
Hello @Nikolai10 

Thank you very much for the reply,  I will try this suggested solution. 

I am using free colab, is it possible to use part of the dataset not all the IAM DB , and do you have any suggestions that would help me in reducing the dataset?

Also I have another question, can I use the code for Arabic handwriting generation, and what are the requirements?

Thanks a lot.

**Comment by Nikolai10** [comment]
Well, I have never encountered OOM while using Google Golab. However, the types of GPUS may vary over time, see [What types of GPUs are available in Colab](https://research.google.com/colaboratory/faq.html).

> I am using free colab, is it possible to use part of the dataset not all the IAM DB , and do you have any suggestions that would help me in reducing the dataset?

One solution would be to use a subset of [listOfFiles](https://github.com/Nikolai10/scrabble-gan/blob/master/src/dinterface/iam_handwriting_db.py#L35), so e.g.

`listOfFiles = listOfFiles[:x]` # with x being your desired dataset size.

In this case, please avoid using the [already preprocessed dataset](https://colab.research.google.com/drive/1-JxJsYbAM9W69nTxSKTp-gR3ofwv5SjM?usp=sharing#scrollTo=znuBc1LYf-sx), section Download Dataset.

> Also I have another question, can I use the code for Arabic handwriting generation, and what are the requirements?

Generally yes, as discussed in #12. Please note that due to time constraints, I won't be able to provide further assistance.
